# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_fittings200_ok import GetCharactersCharacterIdFittings200Ok

class TestGetCharactersCharacterIdFittings200Ok(unittest.TestCase):
    """GetCharactersCharacterIdFittings200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdFittings200Ok:
        """Test GetCharactersCharacterIdFittings200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdFittings200Ok`
        """
        model = GetCharactersCharacterIdFittings200Ok()
        if include_optional:
            return GetCharactersCharacterIdFittings200Ok(
                description = '',
                fitting_id = 56,
                items = [
                    esi_client.models.get_characters_character_id_fittings_item.get_characters_character_id_fittings_item(
                        flag = 'Cargo', 
                        quantity = 56, 
                        type_id = 56, )
                    ],
                name = '',
                ship_type_id = 56
            )
        else:
            return GetCharactersCharacterIdFittings200Ok(
                description = '',
                fitting_id = 56,
                items = [
                    esi_client.models.get_characters_character_id_fittings_item.get_characters_character_id_fittings_item(
                        flag = 'Cargo', 
                        quantity = 56, 
                        type_id = 56, )
                    ],
                name = '',
                ship_type_id = 56,
        )
        """

    def testGetCharactersCharacterIdFittings200Ok(self):
        """Test GetCharactersCharacterIdFittings200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
