# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_loyalty_points200_ok import GetCharactersCharacterIdLoyaltyPoints200Ok

class TestGetCharactersCharacterIdLoyaltyPoints200Ok(unittest.TestCase):
    """GetCharactersCharacterIdLoyaltyPoints200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdLoyaltyPoints200Ok:
        """Test GetCharactersCharacterIdLoyaltyPoints200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdLoyaltyPoints200Ok`
        """
        model = GetCharactersCharacterIdLoyaltyPoints200Ok()
        if include_optional:
            return GetCharactersCharacterIdLoyaltyPoints200Ok(
                corporation_id = 56,
                loyalty_points = 56
            )
        else:
            return GetCharactersCharacterIdLoyaltyPoints200Ok(
                corporation_id = 56,
                loyalty_points = 56,
        )
        """

    def testGetCharactersCharacterIdLoyaltyPoints200Ok(self):
        """Test GetCharactersCharacterIdLoyaltyPoints200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
