# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_insurance_prices200_ok import GetInsurancePrices200Ok

class TestGetInsurancePrices200Ok(unittest.TestCase):
    """GetInsurancePrices200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInsurancePrices200Ok:
        """Test GetInsurancePrices200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInsurancePrices200Ok`
        """
        model = GetInsurancePrices200Ok()
        if include_optional:
            return GetInsurancePrices200Ok(
                levels = [
                    esi_client.models.get_insurance_prices_level.get_insurance_prices_level(
                        cost = 1.337, 
                        name = '', 
                        payout = 1.337, )
                    ],
                type_id = 56
            )
        else:
            return GetInsurancePrices200Ok(
                levels = [
                    esi_client.models.get_insurance_prices_level.get_insurance_prices_level(
                        cost = 1.337, 
                        name = '', 
                        payout = 1.337, )
                    ],
                type_id = 56,
        )
        """

    def testGetInsurancePrices200Ok(self):
        """Test GetInsurancePrices200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
