# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_roles_ok import GetCharactersCharacterIdRolesOk

class TestGetCharactersCharacterIdRolesOk(unittest.TestCase):
    """GetCharactersCharacterIdRolesOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdRolesOk:
        """Test GetCharactersCharacterIdRolesOk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdRolesOk`
        """
        model = GetCharactersCharacterIdRolesOk()
        if include_optional:
            return GetCharactersCharacterIdRolesOk(
                roles = [
                    'Account_Take_1'
                    ],
                roles_at_base = [
                    'Account_Take_1'
                    ],
                roles_at_hq = [
                    'Account_Take_1'
                    ],
                roles_at_other = [
                    'Account_Take_1'
                    ]
            )
        else:
            return GetCharactersCharacterIdRolesOk(
        )
        """

    def testGetCharactersCharacterIdRolesOk(self):
        """Test GetCharactersCharacterIdRolesOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
