# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_universe_moons_moon_id_ok import GetUniverseMoonsMoonIdOk

class TestGetUniverseMoonsMoonIdOk(unittest.TestCase):
    """GetUniverseMoonsMoonIdOk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUniverseMoonsMoonIdOk:
        """Test GetUniverseMoonsMoonIdOk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUniverseMoonsMoonIdOk`
        """
        model = GetUniverseMoonsMoonIdOk()
        if include_optional:
            return GetUniverseMoonsMoonIdOk(
                moon_id = 56,
                name = '',
                position = esi_client.models.get_universe_moons_moon_id_position.get_universe_moons_moon_id_position(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                system_id = 56
            )
        else:
            return GetUniverseMoonsMoonIdOk(
                moon_id = 56,
                name = '',
                position = esi_client.models.get_universe_moons_moon_id_position.get_universe_moons_moon_id_position(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                system_id = 56,
        )
        """

    def testGetUniverseMoonsMoonIdOk(self):
        """Test GetUniverseMoonsMoonIdOk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
