# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_corporations_corporation_id_standings200_ok import GetCorporationsCorporationIdStandings200Ok

class TestGetCorporationsCorporationIdStandings200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdStandings200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCorporationsCorporationIdStandings200Ok:
        """Test GetCorporationsCorporationIdStandings200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCorporationsCorporationIdStandings200Ok`
        """
        model = GetCorporationsCorporationIdStandings200Ok()
        if include_optional:
            return GetCorporationsCorporationIdStandings200Ok(
                from_id = 56,
                from_type = 'agent',
                standing = 1.337
            )
        else:
            return GetCorporationsCorporationIdStandings200Ok(
                from_id = 56,
                from_type = 'agent',
                standing = 1.337,
        )
        """

    def testGetCorporationsCorporationIdStandings200Ok(self):
        """Test GetCorporationsCorporationIdStandings200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
