# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_markets_region_id_history_error520 import GetMarketsRegionIdHistoryError520

class TestGetMarketsRegionIdHistoryError520(unittest.TestCase):
    """GetMarketsRegionIdHistoryError520 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarketsRegionIdHistoryError520:
        """Test GetMarketsRegionIdHistoryError520
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarketsRegionIdHistoryError520`
        """
        model = GetMarketsRegionIdHistoryError520()
        if include_optional:
            return GetMarketsRegionIdHistoryError520(
                error = ''
            )
        else:
            return GetMarketsRegionIdHistoryError520(
        )
        """

    def testGetMarketsRegionIdHistoryError520(self):
        """Test GetMarketsRegionIdHistoryError520"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
