# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_corporations_corporation_id_assets200_ok import GetCorporationsCorporationIdAssets200Ok

class TestGetCorporationsCorporationIdAssets200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdAssets200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCorporationsCorporationIdAssets200Ok:
        """Test GetCorporationsCorporationIdAssets200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCorporationsCorporationIdAssets200Ok`
        """
        model = GetCorporationsCorporationIdAssets200Ok()
        if include_optional:
            return GetCorporationsCorporationIdAssets200Ok(
                is_blueprint_copy = True,
                is_singleton = True,
                item_id = 56,
                location_flag = 'AssetSafety',
                location_id = 56,
                location_type = 'station',
                quantity = 56,
                type_id = 56
            )
        else:
            return GetCorporationsCorporationIdAssets200Ok(
                is_singleton = True,
                item_id = 56,
                location_flag = 'AssetSafety',
                location_id = 56,
                location_type = 'station',
                quantity = 56,
                type_id = 56,
        )
        """

    def testGetCorporationsCorporationIdAssets200Ok(self):
        """Test GetCorporationsCorporationIdAssets200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
