# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.post_characters_character_id_contacts_error520 import PostCharactersCharacterIdContactsError520

class TestPostCharactersCharacterIdContactsError520(unittest.TestCase):
    """PostCharactersCharacterIdContactsError520 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostCharactersCharacterIdContactsError520:
        """Test PostCharactersCharacterIdContactsError520
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostCharactersCharacterIdContactsError520`
        """
        model = PostCharactersCharacterIdContactsError520()
        if include_optional:
            return PostCharactersCharacterIdContactsError520(
                error = ''
            )
        else:
            return PostCharactersCharacterIdContactsError520(
        )
        """

    def testPostCharactersCharacterIdContactsError520(self):
        """Test PostCharactersCharacterIdContactsError520"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
