# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_markets_structures_structure_id200_ok import GetMarketsStructuresStructureId200Ok

class TestGetMarketsStructuresStructureId200Ok(unittest.TestCase):
    """GetMarketsStructuresStructureId200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMarketsStructuresStructureId200Ok:
        """Test GetMarketsStructuresStructureId200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMarketsStructuresStructureId200Ok`
        """
        model = GetMarketsStructuresStructureId200Ok()
        if include_optional:
            return GetMarketsStructuresStructureId200Ok(
                duration = 56,
                is_buy_order = True,
                issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location_id = 56,
                min_volume = 56,
                order_id = 56,
                price = 1.337,
                range = 'station',
                type_id = 56,
                volume_remain = 56,
                volume_total = 56
            )
        else:
            return GetMarketsStructuresStructureId200Ok(
                duration = 56,
                is_buy_order = True,
                issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                location_id = 56,
                min_volume = 56,
                order_id = 56,
                price = 1.337,
                range = 'station',
                type_id = 56,
                volume_remain = 56,
                volume_total = 56,
        )
        """

    def testGetMarketsStructuresStructureId200Ok(self):
        """Test GetMarketsStructuresStructureId200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
