# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_fw_leaderboards_corporations_kills import GetFwLeaderboardsCorporationsKills

class TestGetFwLeaderboardsCorporationsKills(unittest.TestCase):
    """GetFwLeaderboardsCorporationsKills unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFwLeaderboardsCorporationsKills:
        """Test GetFwLeaderboardsCorporationsKills
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFwLeaderboardsCorporationsKills`
        """
        model = GetFwLeaderboardsCorporationsKills()
        if include_optional:
            return GetFwLeaderboardsCorporationsKills(
                active_total = [
                    esi_client.models.get_fw_leaderboards_corporations_active_total_active_total.get_fw_leaderboards_corporations_active_total_active_total(
                        amount = 56, 
                        corporation_id = 56, )
                    ],
                last_week = [
                    esi_client.models.get_fw_leaderboards_corporations_last_week_last_week.get_fw_leaderboards_corporations_last_week_last_week(
                        amount = 56, 
                        corporation_id = 56, )
                    ],
                yesterday = [
                    esi_client.models.get_fw_leaderboards_corporations_yesterday_yesterday.get_fw_leaderboards_corporations_yesterday_yesterday(
                        amount = 56, 
                        corporation_id = 56, )
                    ]
            )
        else:
            return GetFwLeaderboardsCorporationsKills(
                active_total = [
                    esi_client.models.get_fw_leaderboards_corporations_active_total_active_total.get_fw_leaderboards_corporations_active_total_active_total(
                        amount = 56, 
                        corporation_id = 56, )
                    ],
                last_week = [
                    esi_client.models.get_fw_leaderboards_corporations_last_week_last_week.get_fw_leaderboards_corporations_last_week_last_week(
                        amount = 56, 
                        corporation_id = 56, )
                    ],
                yesterday = [
                    esi_client.models.get_fw_leaderboards_corporations_yesterday_yesterday.get_fw_leaderboards_corporations_yesterday_yesterday(
                        amount = 56, 
                        corporation_id = 56, )
                    ],
        )
        """

    def testGetFwLeaderboardsCorporationsKills(self):
        """Test GetFwLeaderboardsCorporationsKills"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
