# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_contacts200_ok import GetCharactersCharacterIdContacts200Ok

class TestGetCharactersCharacterIdContacts200Ok(unittest.TestCase):
    """GetCharactersCharacterIdContacts200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdContacts200Ok:
        """Test GetCharactersCharacterIdContacts200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdContacts200Ok`
        """
        model = GetCharactersCharacterIdContacts200Ok()
        if include_optional:
            return GetCharactersCharacterIdContacts200Ok(
                contact_id = 56,
                contact_type = 'character',
                is_blocked = True,
                is_watched = True,
                label_ids = [
                    56
                    ],
                standing = 1.337
            )
        else:
            return GetCharactersCharacterIdContacts200Ok(
                contact_id = 56,
                contact_type = 'character',
                standing = 1.337,
        )
        """

    def testGetCharactersCharacterIdContacts200Ok(self):
        """Test GetCharactersCharacterIdContacts200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
