# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_corporations_corporation_id_contacts_labels200_ok import GetCorporationsCorporationIdContactsLabels200Ok

class TestGetCorporationsCorporationIdContactsLabels200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdContactsLabels200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCorporationsCorporationIdContactsLabels200Ok:
        """Test GetCorporationsCorporationIdContactsLabels200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCorporationsCorporationIdContactsLabels200Ok`
        """
        model = GetCorporationsCorporationIdContactsLabels200Ok()
        if include_optional:
            return GetCorporationsCorporationIdContactsLabels200Ok(
                label_id = 56,
                label_name = ''
            )
        else:
            return GetCorporationsCorporationIdContactsLabels200Ok(
                label_id = 56,
                label_name = '',
        )
        """

    def testGetCorporationsCorporationIdContactsLabels200Ok(self):
        """Test GetCorporationsCorporationIdContactsLabels200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
