# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_wallet_journal200_ok import GetCharactersCharacterIdWalletJournal200Ok

class TestGetCharactersCharacterIdWalletJournal200Ok(unittest.TestCase):
    """GetCharactersCharacterIdWalletJournal200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdWalletJournal200Ok:
        """Test GetCharactersCharacterIdWalletJournal200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdWalletJournal200Ok`
        """
        model = GetCharactersCharacterIdWalletJournal200Ok()
        if include_optional:
            return GetCharactersCharacterIdWalletJournal200Ok(
                amount = 1.337,
                balance = 1.337,
                context_id = 56,
                context_id_type = 'structure_id',
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                first_party_id = 56,
                id = 56,
                reason = '',
                ref_type = 'acceleration_gate_fee',
                second_party_id = 56,
                tax = 1.337,
                tax_receiver_id = 56
            )
        else:
            return GetCharactersCharacterIdWalletJournal200Ok(
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                description = '',
                id = 56,
                ref_type = 'acceleration_gate_fee',
        )
        """

    def testGetCharactersCharacterIdWalletJournal200Ok(self):
        """Test GetCharactersCharacterIdWalletJournal200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
