# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_corporations_corporation_id_alliancehistory200_ok import GetCorporationsCorporationIdAlliancehistory200Ok

class TestGetCorporationsCorporationIdAlliancehistory200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdAlliancehistory200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCorporationsCorporationIdAlliancehistory200Ok:
        """Test GetCorporationsCorporationIdAlliancehistory200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCorporationsCorporationIdAlliancehistory200Ok`
        """
        model = GetCorporationsCorporationIdAlliancehistory200Ok()
        if include_optional:
            return GetCorporationsCorporationIdAlliancehistory200Ok(
                alliance_id = 56,
                is_deleted = True,
                record_id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetCorporationsCorporationIdAlliancehistory200Ok(
                record_id = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testGetCorporationsCorporationIdAlliancehistory200Ok(self):
        """Test GetCorporationsCorporationIdAlliancehistory200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
