# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_corporations_corporation_id_wallets_division_transactions200_ok import GetCorporationsCorporationIdWalletsDivisionTransactions200Ok

class TestGetCorporationsCorporationIdWalletsDivisionTransactions200Ok(unittest.TestCase):
    """GetCorporationsCorporationIdWalletsDivisionTransactions200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCorporationsCorporationIdWalletsDivisionTransactions200Ok:
        """Test GetCorporationsCorporationIdWalletsDivisionTransactions200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCorporationsCorporationIdWalletsDivisionTransactions200Ok`
        """
        model = GetCorporationsCorporationIdWalletsDivisionTransactions200Ok()
        if include_optional:
            return GetCorporationsCorporationIdWalletsDivisionTransactions200Ok(
                client_id = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_buy = True,
                journal_ref_id = 56,
                location_id = 56,
                quantity = 56,
                transaction_id = 56,
                type_id = 56,
                unit_price = 1.337
            )
        else:
            return GetCorporationsCorporationIdWalletsDivisionTransactions200Ok(
                client_id = 56,
                var_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_buy = True,
                journal_ref_id = 56,
                location_id = 56,
                quantity = 56,
                transaction_id = 56,
                type_id = 56,
                unit_price = 1.337,
        )
        """

    def testGetCorporationsCorporationIdWalletsDivisionTransactions200Ok(self):
        """Test GetCorporationsCorporationIdWalletsDivisionTransactions200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
