# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_client.api.corporation_api import CorporationApi


class TestCorporationApi(unittest.TestCase):
    """CorporationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CorporationApi()

    def tearDown(self) -> None:
        pass

    def test_get_corporations_corporation_id(self) -> None:
        """Test case for get_corporations_corporation_id

        Get corporation information
        """
        pass

    def test_get_corporations_corporation_id_alliancehistory(self) -> None:
        """Test case for get_corporations_corporation_id_alliancehistory

        Get alliance history
        """
        pass

    def test_get_corporations_corporation_id_blueprints(self) -> None:
        """Test case for get_corporations_corporation_id_blueprints

        Get corporation blueprints
        """
        pass

    def test_get_corporations_corporation_id_containers_logs(self) -> None:
        """Test case for get_corporations_corporation_id_containers_logs

        Get all corporation ALSC logs
        """
        pass

    def test_get_corporations_corporation_id_divisions(self) -> None:
        """Test case for get_corporations_corporation_id_divisions

        Get corporation divisions
        """
        pass

    def test_get_corporations_corporation_id_facilities(self) -> None:
        """Test case for get_corporations_corporation_id_facilities

        Get corporation facilities
        """
        pass

    def test_get_corporations_corporation_id_icons(self) -> None:
        """Test case for get_corporations_corporation_id_icons

        Get corporation icon
        """
        pass

    def test_get_corporations_corporation_id_medals(self) -> None:
        """Test case for get_corporations_corporation_id_medals

        Get corporation medals
        """
        pass

    def test_get_corporations_corporation_id_medals_issued(self) -> None:
        """Test case for get_corporations_corporation_id_medals_issued

        Get corporation issued medals
        """
        pass

    def test_get_corporations_corporation_id_members(self) -> None:
        """Test case for get_corporations_corporation_id_members

        Get corporation members
        """
        pass

    def test_get_corporations_corporation_id_members_limit(self) -> None:
        """Test case for get_corporations_corporation_id_members_limit

        Get corporation member limit
        """
        pass

    def test_get_corporations_corporation_id_members_titles(self) -> None:
        """Test case for get_corporations_corporation_id_members_titles

        Get corporation's members' titles
        """
        pass

    def test_get_corporations_corporation_id_membertracking(self) -> None:
        """Test case for get_corporations_corporation_id_membertracking

        Track corporation members
        """
        pass

    def test_get_corporations_corporation_id_roles(self) -> None:
        """Test case for get_corporations_corporation_id_roles

        Get corporation member roles
        """
        pass

    def test_get_corporations_corporation_id_roles_history(self) -> None:
        """Test case for get_corporations_corporation_id_roles_history

        Get corporation member roles history
        """
        pass

    def test_get_corporations_corporation_id_shareholders(self) -> None:
        """Test case for get_corporations_corporation_id_shareholders

        Get corporation shareholders
        """
        pass

    def test_get_corporations_corporation_id_standings(self) -> None:
        """Test case for get_corporations_corporation_id_standings

        Get corporation standings
        """
        pass

    def test_get_corporations_corporation_id_starbases(self) -> None:
        """Test case for get_corporations_corporation_id_starbases

        Get corporation starbases (POSes)
        """
        pass

    def test_get_corporations_corporation_id_starbases_starbase_id(self) -> None:
        """Test case for get_corporations_corporation_id_starbases_starbase_id

        Get starbase (POS) detail
        """
        pass

    def test_get_corporations_corporation_id_structures(self) -> None:
        """Test case for get_corporations_corporation_id_structures

        Get corporation structures
        """
        pass

    def test_get_corporations_corporation_id_titles(self) -> None:
        """Test case for get_corporations_corporation_id_titles

        Get corporation titles
        """
        pass

    def test_get_corporations_npccorps(self) -> None:
        """Test case for get_corporations_npccorps

        Get npc corporations
        """
        pass


if __name__ == '__main__':
    unittest.main()
