# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_universe_asteroid_belts_asteroid_belt_id_position import GetUniverseAsteroidBeltsAsteroidBeltIdPosition

class TestGetUniverseAsteroidBeltsAsteroidBeltIdPosition(unittest.TestCase):
    """GetUniverseAsteroidBeltsAsteroidBeltIdPosition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUniverseAsteroidBeltsAsteroidBeltIdPosition:
        """Test GetUniverseAsteroidBeltsAsteroidBeltIdPosition
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUniverseAsteroidBeltsAsteroidBeltIdPosition`
        """
        model = GetUniverseAsteroidBeltsAsteroidBeltIdPosition()
        if include_optional:
            return GetUniverseAsteroidBeltsAsteroidBeltIdPosition(
                x = 1.337,
                y = 1.337,
                z = 1.337
            )
        else:
            return GetUniverseAsteroidBeltsAsteroidBeltIdPosition(
                x = 1.337,
                y = 1.337,
                z = 1.337,
        )
        """

    def testGetUniverseAsteroidBeltsAsteroidBeltIdPosition(self):
        """Test GetUniverseAsteroidBeltsAsteroidBeltIdPosition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
