# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from esi_client.api.insurance_api import InsuranceApi


class TestInsuranceApi(unittest.TestCase):
    """InsuranceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InsuranceApi()

    def tearDown(self) -> None:
        pass

    def test_get_insurance_prices(self) -> None:
        """Test case for get_insurance_prices

        List insurance levels
        """
        pass


if __name__ == '__main__':
    unittest.main()
