# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from esi_client.models.get_characters_character_id_industry_jobs200_ok import GetCharactersCharacterIdIndustryJobs200Ok

class TestGetCharactersCharacterIdIndustryJobs200Ok(unittest.TestCase):
    """GetCharactersCharacterIdIndustryJobs200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCharactersCharacterIdIndustryJobs200Ok:
        """Test GetCharactersCharacterIdIndustryJobs200Ok
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCharactersCharacterIdIndustryJobs200Ok`
        """
        model = GetCharactersCharacterIdIndustryJobs200Ok()
        if include_optional:
            return GetCharactersCharacterIdIndustryJobs200Ok(
                activity_id = 56,
                blueprint_id = 56,
                blueprint_location_id = 56,
                blueprint_type_id = 56,
                completed_character_id = 56,
                completed_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cost = 1.337,
                duration = 56,
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                facility_id = 56,
                installer_id = 56,
                job_id = 56,
                licensed_runs = 56,
                output_location_id = 56,
                pause_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                probability = 1.337,
                product_type_id = 56,
                runs = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                station_id = 56,
                status = 'active',
                successful_runs = 56
            )
        else:
            return GetCharactersCharacterIdIndustryJobs200Ok(
                activity_id = 56,
                blueprint_id = 56,
                blueprint_location_id = 56,
                blueprint_type_id = 56,
                duration = 56,
                end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                facility_id = 56,
                installer_id = 56,
                job_id = 56,
                output_location_id = 56,
                runs = 56,
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                station_id = 56,
                status = 'active',
        )
        """

    def testGetCharactersCharacterIdIndustryJobs200Ok(self):
        """Test GetCharactersCharacterIdIndustryJobs200Ok"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
