# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    The version of the OpenAPI document: 1.19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GetIndustryFacilities200Ok(BaseModel):
    """
    200 ok object
    """ # noqa: E501
    facility_id: StrictInt = Field(description="ID of the facility")
    owner_id: StrictInt = Field(description="Owner of the facility")
    region_id: StrictInt = Field(description="Region ID where the facility is")
    solar_system_id: StrictInt = Field(description="Solar system ID where the facility is")
    tax: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Tax imposed by the facility")
    type_id: StrictInt = Field(description="Type ID of the facility")
    __properties: ClassVar[List[str]] = ["facility_id", "owner_id", "region_id", "solar_system_id", "tax", "type_id"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetIndustryFacilities200Ok from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GetIndustryFacilities200Ok from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "facility_id": obj.get("facility_id"),
            "owner_id": obj.get("owner_id"),
            "region_id": obj.get("region_id"),
            "solar_system_id": obj.get("solar_system_id"),
            "tax": obj.get("tax"),
            "type_id": obj.get("type_id")
        })
        return _obj


